### ISSUE TITLE
Convert .docx paper to Markdown equivalent

### ISSUE THREAD

**Issue by miike** [OpenSourceMalaria/OSMSeries4Paper1#1]
Convert the current state of the paper (as a docx) to Markdown so that it can be rendered on Github online. Need to find a way to do this long term.

**Comment by mattodd** [comment]
Would be good to see what this looks like. I understand this is doable, but not from within Word http://johnmacfarlane.net/pandoc/

**Comment by miike** [comment]
PR is [here](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/pull/2). I've merged in and you can see what it looks like [here](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/blob/master/OSM_Series_4_Paper1.md)

**Comment by mattodd** [comment]
Very nice - formatting retained and pictures look fine.

On 30 March 2015 at 21:42, miike <notifications@github.com> wrote:

>  PR is here <https://github.com/OpenSourceMalaria/OSMSeries4Paper1/pull/2>.
> I've merged in and you can see what it looks like here
> <https://github.com/OpenSourceMalaria/OSMSeries4Paper1/blob/master/OSM_Series_4_Paper1.md>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSMSeries4Paper1/issues/1#issuecomment-87631354>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by miike** [comment]
Formatting looks good but the images had to be added by hand unfortunately. I think pandoc might be able to do that automagically but I'm not 100% sure yet.
