### ISSUE TITLE
How do we "reject" a commit on a Pull Request?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#12]
As an experiment in collaborative writing (mattodd/OSM_To_Do_List#536 <-- why isn't this working, by the way. [Should](https://github.com/github/markup/issues/154).) we've started on submitting characterisation files using pull requests to ensure that data can be checked/approved.

@david1597 submitted [this Pull Request](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/pull/11). Before approving it we did an experiment: @edwintse submitted a [(bad, very bad) suggestion for a change](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/pull/11/commits/7355a75a5477d44e040025f8c7919bcfe261cd7c) to David's files.

What I want to do is _reject that second commit, and only merge the first_. There's no obvious option for this. [Looking around](https://stackoverflow.com/questions/7217031/github-accept-pull-request-but-only-some-commits), it seems complicated. Is there a simple way to do this?

**Comment by TrentWallis** [comment]
I'm no expert here, but can you click on the individual links (on the right, 58dca72 for David's) and just approve those?
![individual link](https://user-images.githubusercontent.com/8891944/29501037-bec1058e-8668-11e7-896a-b885c9082bac.jpg)

**Comment by egonw** [comment]
I think the approach is to ask the author for a revision... and the author of the PR can remove the patch...

**Comment by miike** [comment]
As @egonw has mentioned above - as far as I know you can't cherry pick commits (the Git lingo) in the UI without using the command line.

A reviewer for the pull request can leave a comment or request changes for the commit to either be reverted, or alternately make a new commit that reverses the changes and then push this to the same branch. This would avoid having to go through the process of cherry picking commits from a branch.

**Comment by mattodd** [comment]
OK, so asking the first person to resubmit the PR with the right version. Accepting all the requests should end up with the desired (most recent) version winning the day. Funny there is no "Merge at this point, ignore later" button.

**Comment by edwintse** [comment]
We've requested a change but when we go to the pull request there is no option to revert the undesired commit. It looks like all the pull requests will be merged, including the one we don't want. Is the only option to resubmit the original pull request?

![screen shot 2017-08-25 at 12 13 43 pm](https://user-images.githubusercontent.com/18062981/29696869-e3dc57d2-898e-11e7-85da-1d49bf20a9ee.png)

**Comment by miike** [comment]
@edwintse When you mark 'Changed requested' on a pull request this will notify the author of the pull request to make these changes. All commits in the pull request will be merged (rather than selectively) so if there's a change you want to reverse the best way is to reverse the change on your OSM-S-219 branch, commit this change and then push up to the OSM-S-219 branch again. 

Once the new commit is on Github it will automatically be added to the pull request.

**Comment by edwintse** [comment]
@miike I see. So once the reversed commit is resubmitted to the branch, there will then be 3 commits. The description for the "merge pull request" button says that "all commits from the branch will be added to the base branch". Is there no option to just merge the latest pull request or is this the same thing?

**Comment by miike** [comment]
Yep - it's just the same thing. Merging the pull request will merge all commits in that branch to the base branch.

**Comment by david1597** [comment]
@mattodd Cross-referencing issues from the other repos requires putting OpenSourceMalaria/RepoName before the issue number. eg. OpenSourceMalaria/OSM_To_Do_List#536

**Comment by maximemer** [comment]
Hi David, 
Thanks for submitting this but unfortunately we wont be taking this PR. First it seems to copy a lot of the functionality of the none moveable version so it is not optimal and we are more eager to take fixes to existing code than entirely new features as it only creates us more burden on support.
Maxime

**Comment by CodetechDevs** [comment]
that way
