### ISSUE TITLE
OSM Series 4 Communication Instead?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#15]
Further to the planning for the main, first Series 4 paper (OpenSourceMalaria/OSM_To_Do_List#532), I get the sense that there is a barrier to progress on the writing of this [manuscript](http://tinyurl.com/OSM-S4-Paper1) because of the size of the task. There is so much to go in that perhaps we should consider a smaller endeavor first.

What would people say to our trying to write up a communication first, followed by everything in a full paper? This is how we used to do things.

We would need to select data to include - the important features of the series as drugs, illustrated with selected examples rather than every compound.

A communication ideally needs a punchline - some finding that justifies the need for publication in this form. We are already there in the sense that we have potent, _in vivo_ active compounds active against drug resistant strains, in the public domain as part of an ongoing project. My feeling here is that the identification of a highly potent, new, soluble molecule in the series would be the extra item we need for the paper, and a good candidate is the compound identified (OpenSourceMalaria/OSM_To_Do_List#529), and now resynthesized (OpenSourceMalaria/OSM_To_Do_List#525) by David. This compound, along with others, is in the air to Dundee (OpenSourceMalaria/Series4#10). If it's as potent as we think, then I suggest we have it evaluated at Monash for solubility and basic _in vitro_ DMPK. Then we publish a communication, highlighting what needs to be done next. We include some MoA work with Kiaran Kirk, but not the predictive modeling (OpenSourceMalaria/OSM_To_Do_List#538).

What say you, potential co-authors?

**Comment by MFernflower** [comment]
I second this idea

**Comment by cdsouthan** [comment]
Not keen,  we have more than enough for two full papers,  if we can decide the split.  By the time we have gone through the palaver of  drafting a paper anyway you save very little time with a short  compared to long one, and the former have less impact.

**Comment by MedChemProf** [comment]
I tend to agree with the two paper approach over the communication then full paper due to the potential larger impact of the two concurrent publications. Initial thought is to have one paper focus only on the SAR of potency and the second focus on ADMET optimization with the compounds we have data on.

**Comment by cdsouthan** [comment]
Good idea @MedChemProf. Certainly two substantial papers could go back-to-back. Sure would be quite a slog but thats our job and would be a surfacing to be proud of (as well as a funder-pleaser).  Note also there are at least some economies of scale to writing up a double-header compared to separate journals (same house style etc).  May even be other ways of splitting e.g. early and later?   Obviously good idea to iterate with Editors beforehand on the plan but I cant imagine ACS Cent Sci telling us to bugger off elsewhere.  Especially when we got them a stonking Altmetric and a Dereck Low write up.  There should be at least a finite chance he could pick the  double-header up as well.

**Comment by david1597** [comment]
My preference is to head down the communication route. 

Assuming potency is as expected for OpenSourceMalaria/OSM_To_Do_List#529 there is a story to tell, and there will be a fuller story to tell later - building and expanding on that in a fuller paper. 

We do seem to have stalled on this writing of paper 1, and my personal feeling is that this is simply down to the size of the task. There's a huge amount of data and it's perhaps more difficult to find that first story, and find where the cutting point is between the first and subsequent papers.

**Comment by alintheopen** [comment]
I'd suggest seeing what the potency data tells us and then coming back to this discussion. Certainly it is a good idea for us to approach a journal before committing to one publication approach over the other, but of course we need some proposals in place too.

**Comment by mattodd** [comment]
Closing this old issue as outdated given that we're nearing submission of a main paper, after smaller papers on bioisosteres and telesubst.
