### ISSUE TITLE
A Note on Referencing Online Resources

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#17]
As we start to write more of the Series 4 paper in the coming weeks, I wanted to make a quick note about how we refer to data. [We dealt with these issues on the fly with the first OSM paper](https://intermolecular.wordpress.com/2016/09/14/open-source-malarias-first-paper/), but I wanted to flag this up early.

The [paper itself](https://docs.google.com/document/d/1vlOHNo9bxmx24KmNdJz5ZmjXyVP9uZoHJcnGj181NZE/edit) will sit at the centre of a very large amount of supporting data (compound synthesis, biological results) all of which will/should be in disparate online resources like ELNs. For writing the paper itself we can simply refer to those resources directly using hyperlinks. 

However, the paper needs to be a self-consistent object that lasts forever once published. We have to entertain the possibility that ELN manufacturers or Github go out of business. So for publication all the data we refer to will need to sit either at the journal itself or on a University repository (or some other as-permanent-as-it-gets resource). Journals are obviously happy to take a fair amount of SI, but for some of the larger things we're probably going to need those uni repos, and the permanent handles they provide for content. 

The data at the journal, or on Uni repositories, can contain the original links to ELNs etc, to clarify where the data were first posted, but it must not affect the paper's conclusions if those links die.

So we all write the paper as normal, but we immortalise the links to data at the end.

Here's the whiteboard version of this point, from today.

![img_20180404_160003](https://user-images.githubusercontent.com/4386101/38313621-d01063f0-3867-11e8-98a4-ff20eaa7d8df.jpg)

**Comment by MedChemProf** [comment]
@mattodd I know I have been absent from the Series 4 discussions since last summer, but I am now back from my deployment. I will be back at work next week and I will dig into things ASAP. Really good to be back.

**Comment by mattodd** [comment]
Note also that we have a good place for the temporary assembly of "supporting information" at https://github.com/OpenSourceMalaria/OSMSeries4Paper1/tree/master/Experimental which can act like a Dropbox-like place for datasets and anything else.

**Comment by cdsouthan** [comment]
Good not only to see editing surge @mattodd  but also to welcome @MedChemProf (safely) back 

n.b. 1) Figshare will do nicely as permanent repos for SI 

n.b. 2) I can assist someone with PubChem BioAssay submissions, including mediating direct contacts with the PubChem team.   Given the daunting backlog we could restrict to just front runners and a few key inactive controls.  The worthy person who accepts this challenge would need to set up a submitter account with OSM affiliation (I could submit frontrunners on our behalf but it would look a bit odd to have my consultancy affiliation https://www.ncbi.nlm.nih.gov/pcsubstance?term=%22TW2Informatics%22%5BSourceName%5D%20AND%20hasnohold%5Bfilt%5D)
