### ISSUE TITLE
Graphical Abstract

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#18]
@holeung added a candidate graphical abstract to the [paper](https://docs.google.com/document/d/1vlOHNo9bxmx24KmNdJz5ZmjXyVP9uZoHJcnGj181NZE/edit). I've commented and suggested something else. There is now a Graphical Abstract folder on this repository so people can add raw files and ideas to that (click on "OSMSeries4Paper1" above if you're rusty on your navigation). Discuss below or on the paper itself. 

The Graphical abstract is probably the thing that we'll be tweaking to the last, so this Issue is merely to provide a place to discuss it, not to imply that it's currently the top item on the To Do list.

**Comment by MedChemProf** [comment]
@mattodd I am starting to dig into things again and I just had a question on protocol. Should my edits in regards to the Series 4 paper be on the [paper](https://docs.google.com/document/d/1vlOHNo9bxmx24KmNdJz5ZmjXyVP9uZoHJcnGj181NZE/edit) itself? On the [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/What-is-OSM-Series-4%3F)? or both?

Apologies if this was already covered elsewhere. Thanks. Chase

**Comment by mattodd** [comment]
Hi @MedChemProf - there are some FAQs [here](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/wiki), pointing to OpenSourceMalaria/OSM_To_Do_List#532. In general the wiki needs to be in good shape (since we can take things from there for the paper) but if you want to add instead to the paper directly, go right ahead. If you decide to write a section, or do something significant, maybe create an FYI-type Issue here.

**Comment by MedChemProf** [comment]
@mattodd Got it and thanks. One other question for the group. I wanted to edit one of the images on the wiki to update some of the information. I went to try and download the original Chemdraw .cdxml file to edit and then upload the updated file as well as the updated .png file. My perplexing problem is that github is not allowing me to download the .cdxml file, but instead opens it up in a new window as though I am going to edit the contents of the file in markdown directly. I have tried multiple things to try and force the Chemdraw file to be downloaded. Is there a trick to getting this to work? (Also, I am not going to be able to install the github desktop app on my work computer.)

**Comment by drc007** [comment]
The only way to do it that I've found is to click on the link to the file, when open in the browser choose "edit". The XML should be displayed, copy and paste this into a text editor (I used BBEdit) and then save it to my file.cdxml.

It can then be opened in Chemdraw.

**Comment by MedChemProf** [comment]
@drc007 Thank you!

**Comment by MedChemProf** [comment]
Actually, I have been having problems with that route also. I read through the FAQ's and most likely missed it, but is there a standard template for Chemdraw to use? I have customized my Chemdraw for my teaching purposes and I was looking for another template to be more consistent with what is already being used on the wiki.

**Comment by cdsouthan** [comment]
Nothing personal of course,  but considering our overriding comitment to "Openness" our apparent collective lock-in to Chemdraw seems anachronistic.   Chem4Word anyone?  (with PubChem import)

**Comment by danaklug** [comment]
Added a few options to the graphical abstract folder using @holeung 's PfATP4 image and the OHOH compound as the frontrunner.
