### ISSUE TITLE
Update SAR for triazole side chain modification - Phenyl-based analogs

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#20]
Placeholder Issue for updates to SAR involving simple alterations to phenyl-based substituents.

[Syngene 2015 Data](https://malaria.ourexperiment.org/biological_data/13863/Activity_Data_from_Syngene__November_2015_Compounds.html) added to [relevant page of S4 wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Modification-of-the-Triazole-Substitution) indicating high levels of dependence of potency on substitution pattern of phenyl ring attached to triazole (main comparison is MMV663915 with isomers and des-chloro compound).
Remaining issue - remove odd green "Good to Go" in image - done 29/4/18

**Comment by mattodd** [comment]
[Added scheme showing CN and Cl well tolerated on triazole phenyl substituent](https://github.com/OpenSourceMalaria/Series4/wiki/Modification-of-the-Triazole-Substitution). Data from [2014 GSK single shot potency analysis](https://malaria.ourexperiment.org/biological_data/10252/Single_Shot_Potencies_for_Compounds_Submitted_to_GSK.html) (and subsequent zoom-in on active compounds).

**To Do**: Need to deal with why OCHF2 has been the default para substituent, when it appears that CN gives better predicted solubility?

<a href="url"><img src="https://github.com/OpenSourceMalaria/Series4/blob/master/Wiki%20Files/SAR%20Triazole%20Phenyl%20Para%20Solubility.png?raw=true" align="centre" height="190" ></a>

**Comment by MedChemProf** [comment]
I had added a similar series to the Reversed Amide section late last week. https://github.com/OpenSourceMalaria/Series4/wiki/Pyrazine-Side-Chain-Modifications---Reversed-Amides

**Comment by mattodd** [comment]
Great @MedChemProf  - can I just check that the image files (cdx and png etc) are in [the relevant repo folder](https://github.com/OpenSourceMalaria/Series4/tree/master/Wiki%20Files), and that the data are in the Master List?

**Comment by MedChemProf** [comment]
@mattodd The files were added to the [Files from Claire Littler](https://github.com/OpenSourceMalaria/Series4/tree/master/Wiki%20Files/Files%20from%20Claire%20Littler) folder which contained the files for the original Reversed Amide SAR discussion prior to my edits.

**Comment by mattodd** [comment]
Tweaked and updated/uploaded schemes on [wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Modification-of-the-Triazole-Substitution) showing
i) CF3 and CHF2 better than CH3, and
ii) Pyridine no good.
Data from [2014](https://malaria.ourexperiment.org/biological_data/11216/Evaluation_of_Latest_Series_4_Analogs_in_Ether_and_Amide_Series.html).

**Comment by mattodd** [comment]
Added MMV675948 (OSM-S-265) [to wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Modification-of-the-Triazole-Substitution) as another example of potent p-CN analog, from [2014 Syngene assay](https://malaria.ourexperiment.org/biological_data/11216/Evaluation_of_Latest_Series_4_Analogs_in_Ether_and_Amide_Series.html).
