### ISSUE TITLE
Update hERG Section on S4 Wiki

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#23]
@edwintse is working on updating all hERG data acquired in Series 4, on [the S4 wiki](https://github.com/OpenSourceMalaria/Series4/wiki/hERG-Activity), in advance of choosing data for the paper. This is a placeholder issue, with further component items shown as comments below.

**Comment by mattodd** [comment]
First item. The [data shown here from May 2014](https://malaria.ourexperiment.org/biological_data/10078/Screening_of_hERG_Activity_in_Series_4_Compounds.html) plus seemingly *two* output posts in September 2014 [here](https://malaria.ourexperiment.org/biological_data/month/1409529600)?
@edwintse can you ensure that these data are on the wiki? 
And that there is a link to that page on the "Sources of Data" page (maybe one line just on hERG containing multiple links out?)
And similar link on the "[done bio](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections#done)" section of the wiki.
And that the primary data (i.e. all the attachments to the posts for this evaluation - files, pix, chemdraws) are uploaded to the [relevant folder on the Github repo](https://github.com/OpenSourceMalaria/Series4/tree/master/Molecule%20Evaluations/2014%20hERG) 
Once done, thumbs-up this comment.
Cross-reference: OpenSourceMalaria/OSM_To_Do_List#211

**Comment by edwintse** [comment]
All old data has been linked in the wiki.
All attachments have been uploaded to the relevant folder.
