### ISSUE TITLE
Update liver stage data section on wiki

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/OSMSeries4Paper1#24]
I am currently working on updating the liver stage data acquired in Series 4, on the S4 wiki, in advance of choosing data for the paper. This is a placeholder issue. Any discussion on this data will be over at https://github.com/OpenSourceMalaria/Series4/issues/35.

**Comment by mattodd** [comment]
Closing issue as no longer needed. Everything linked to on wiki.
