### ISSUE TITLE
SAR data schemes vs tables for publication?

### ISSUE THREAD

**Issue by danaklug** [OpenSourceMalaria/OSMSeries4Paper1#26]
Hi all, I'm Mat's new postdoc. Working on getting the bulk of the SAR discussion for the paper done and was thinking of presenting the data in tables rather than the schemes we currently have. I think it's a bit clearer for the reader and a good way to organize (example below). I think it might be good to have some physchem data (clogP and LLE for example) included as well as one of the stated aims from the beginning was to improve ADME - maybe a separate table for clearance, solubility, etc. as that data is a bit more rare.

Any feedback on how best to present the SAR data and discussion is appreciated, as well as any thoughts about how to best share the work in progress files.

![Series_4_example_table](https://user-images.githubusercontent.com/53487492/62369228-d812b480-b526-11e9-845e-1a8b21f40d50.PNG)

**Comment by drc007** [comment]
@danaklug I'd agree tables are much easier for the reader to follow. 

Were all the EC50 results from the same assay? Were cLogP all calculated using the same software and the same tautomeric form?

IS LLE an appropriate metric to use for this assay?

**Comment by danaklug** [comment]
There are a couple of different EC50 assays on this project, which I was thinking we could address in footnotes to the table. I calculated cLogP using DataWarrior with the SMILES string from the master compound list.

Even though we're using a phenotypic assay and LLE won't be able to tell us anything about binding, I think it's still a nice way to consider potency and clogP simultaneously. Maybe the best approach to this would be to see if there are any LLE trends or features actually worth discussing... if not, we could drop it.

**Comment by danaklug** [comment]
I've started a Google doc for the tables and any comments about SAR discussion:

https://docs.google.com/document/d/1qTea5airMy5Yobb8_NdFOapGsxiKOTnz9_BeBiCjL4g/edit?usp=sharing

**Comment by danaklug** [comment]
As most feedback I've gotten is in favor of tables, I have moved the SAR tables to the main draft in place of figures.

**Comment by MedChemProf** [comment]
@danaklug I made some edits to the "Triazole: Substituted phenyls" table in the shared Google Doc. I also updated the Master Spreadsheet to include some missing analogs that are now also included in the table. I also noticed that there was a title for the table "Pyrazine: Amines and reverse amides", but no table yet. I can add that one in over the next few days. I only had one question concerning the LLE calculation. I used DatWarrior to calculated the LogP values, but I was getting different LLE numbers. Would you be able to share how you did the calculations for LLE? Thanks.

**Comment by danaklug** [comment]
Thanks! I have migrated most of the tables over to the main manuscript Google Doc, which I will do for the added triazole analogs. 

For LLE, I converted potency to pEC50 and subtracted clogP as set up in the spreadsheet below (just a cleaned up version of the master compound list with columns for these calculations added). Let me know if it needs to be adjusted.

[Series_4_Paper.xlsx](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/3516299/Series_4_Paper.xlsx)

**Comment by edwintse** [comment]
Just coming back to this, I'm wondering if a single figure would actually be better to summarise the SAR? We've currently got at least 10 separate tables of SAR with 10-20 compounds in each. All in all, they take up quite a lot of space and not every compound in the table could be considered important. I was thinking something along the lines of this instead? This way we can cut back on the number of compounds in the actual paper to just show the key SAR (e.g. EDG/EWG/sterics/etc.) and have the full SAR tables in the SI instead.

![Series 4 SAR Summary](https://user-images.githubusercontent.com/18062981/66756738-8ffeff00-ee92-11e9-9a63-65c1622a7b35.jpeg)

**Comment by cdsouthan** [comment]
It seems a good idea but raises the challenge of collating the SAR tables for the SI and the compound number mapping to MMV IDs ect.  As @mattodd already mentioned any forking of datasheets is perilous. Why not plan to drop the entire Master Sheet version into Figshare?

**Comment by edwintse** [comment]
Agreed. I'd still rather deal with the SAR tables as part of the SI than in the actual paper. In any case, we would have to fork the Master Sheet at least once and clean it to only include Series 4 compounds and the relevant biological data. It would be good to upload this or a link to this as part of the SI. We could use MMV or OSM numbers but I'm a bit worried that the numbers would jump around too much and make things a bit trickier to follow.

The Master Sheet is still at [this URL](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618).

**Comment by cdsouthan** [comment]
OK, I defer to those doing the hard work of drafting of course.  However, OSM should not be shy about challenging precedents,  in this case by uploading the whole Master Sheet as the de facto SI  even if it has some non-series 4 data in it (that we are open about anyway).  The journal is unlikely to chastise us for the additional disclosures.  Then you just have to key the example numbers against the MMV plus OSM numbers (possibly PubChem CIDs also we'll see)

**Comment by MedChemProf** [comment]
I agree with @edwintse on his suggestion to reduce the number of tables by providing some of the summary figures he suggested and list key molecules versus the number currently in the tables. I also think the figures should have some sort of simple color coding to denote increase/decrease in activity versus the larger functional group changes. I also tend to agree that the compound numbering would jump around quite a bit if we use either the MMV or OSM numbers. Might I suggest that we number the compounds in the paper 1,2,...N and provide a table in the SI that links the paper compound numbers to MMV or OSM?

**Comment by danaklug** [comment]
@edwintse Agree that the tables are too big as is. One point I would make is that tables allow us to present other data such as clogP/LLE that I think would be too much text for a figure. Although I don't think that data is necessary to tell the story, as a reader I like to see med chem groups pay at least some attention to properties as well as potency, especially in late stage optimization. Just a thought.

I'm also thinking that we don't want to make it too much hard work to track down the manuscript compounds on the spreadsheet... what about something like this? We could make one for each set of compounds in Ed's figure - it takes up more space (still better than what we have now) but also allows for the inclusion of more information.

![image](https://user-images.githubusercontent.com/53487492/66812212-61ccfe00-ef2a-11e9-9423-a8c902a01dae.png)

**Comment by edwintse** [comment]
I'll start having a look at condensing these down accordingly. Colour coding is definitely a good idea to make the changes even easier to compare.

It would definitely be easiest to just upload the Master Sheet as is for the SI but if I was an outsider looking at the sheet for the first time, it would be a bit daunting with so many compounds (not all of which being relevant) and columns (a lot of which are blank). I would prefer a more concise/cleaned version myself.

In terms of numbering and MMV/OSM codes, this is what I did for my thesis so we could do something similar.

![Screen Shot 2019-10-15 at 2 08 34 pm](https://user-images.githubusercontent.com/18062981/66835023-b0908d00-ef56-11e9-8d17-15bbd01e700c.png)

**Comment by holeung** [comment]
I agree with @edwintse that it help to have a summary/highlights table of SAR in the main paper and include the full dataset as Supplementary Materials or as part of an online data archive.
