### ISSUE TITLE
Supplementary Information

### ISSUE THREAD

**Issue by danaklug** [OpenSourceMalaria/OSMSeries4Paper1#28]
I've created a Google doc for the SI file [here](https://docs.google.com/document/d/18PH0CwMHFl4YCdDBXCXS8YA_IdHmxW-2HrTqiiJA9MY/edit?usp=sharing). The main things that will go in this file are tables of additional compounds to fill out SAR, additional synthetic schemes, and characterization of synthesized compounds.

I have also compiled a simplified Google sheet [here](https://docs.google.com/spreadsheets/d/1vCXWGBo9Z0HLQVRHNz3fOIF4BAwivjYC4oCFk3lRDu8/edit?usp=sharing) that has an added column to designate which table(s) the compound appears in and whether the experimental has been completed. 

Hope this is helpful!

**Comment by MedChemProf** [comment]
See Issue #54
