### ISSUE TITLE
Completion of Metabolomics Section

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#36]
Two things needed:

We have shortened and edited the schemes to try to keep the summary in the main paper, and move the extra info into the SI. We need two things:

1) Anubhav and Darren's views on whether the pared back text is OK. Ultimately the idea is to show a clustering of the results with other PfATP4 inhibitors and a distinction wiith the non-PfATP4 compounds. 

2) Ultimately Figure 11 (as it stands at the moment) is nicely showing those comparisons. It's currently a little small and we wondered whether Anubhav or Darren would be prepared to edit it to make it a little easier to see the text and read the captions. There may be some back and forth on what works best, so we can consult on all that here, and share drafts, if that helps.

**Comment by mattodd** [comment]
Anubhav kindly replied by email "I have added a bit of clarification in the draft of the paper regarding the last sentence in the metabolomics section. It's meant to explain the specificity observed with PfATP4 inhibitors in spite of some similarity in profile observed with the digestive vacuole targeting drugs. I am happy with the pared back text as it stands and can modify figure 11 to make the text bigger etc and will upload the new(er) versions on the GHI you created for that. (Darren Creek copied in)

One point regarding the nomenclature of the compounds- I had used the active analogue OSM-S-313, and the inactive analogue OSM-S-291 for the experiments and the write up. In the latest draft of the paper, these have been replaced by OSM-S-218 (active) and MMV689968 (inactive). If this is correct and then that's what should be used in the figure and the legend and I'll need to update that. If you could confirm either way, that would be great."

@edwintse @danaklug could this issue of compound numbering please be checked when you've a moment?

**Comment by danaklug** [comment]
@mattodd Pretty sure OSM-S-218 is the correct nomenclature. I checked the structure of OSM-S-313 and it looked like an intermediate - didn't contain the triazolopyrazine core - and didn't have any potency data. OSM-S-218 has an internal ID of AEW 313-1 which we think is how the mix-up happened (it is active and has the expected structure).

**Comment by mattodd** [comment]
Hi - we need to be sure about the compounds. The compounds originally shipped by @alintheopen are shown at OpenSourceMalaria/OSM_To_Do_List#469 - is the numbering wrong for those structures? More discussion at OpenSourceMalaria/OSM_To_Do_List#524. I realise we don't have a section on metabolomics on the wiki, but should.

Attached is the Excel file that went along with the shipment to Darren Creek on 20th Jan 2017.

Separately, I'm happy with the edits by Anubhav in the paper, and will resolve them, so we just need clarity on the compounds and nomenclature to ensure that the compounds tested are those we think were tested.

[Darren Creek Compounds 170117.xlsx](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/5980834/Darren.Creek.Compounds.170117.xlsx)

**Comment by mattodd** [comment]
Just re the diagram (Fig 10 at the moment) I guess we need a new version that has slightly larger text so it can be read. Perhaps panels B and C below panel A? Files can be shared here.

**Comment by danaklug** [comment]
@mattodd Just checked against the OSM master sheet and the SMILES of OSM-S-218 matches the structure labeled OSM-S-313 in https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/469. The SMILES of OSM-S-313 in the master sheet is this: 

![image](https://user-images.githubusercontent.com/53487492/107933571-ce209d00-6f76-11eb-95a9-373219e40a11.png)

So if we are going by the mater sheet numbering, OSM-S-218 is the correct OSM ID.

**Comment by danaklug** [comment]
> Separately, where are the old files from earlier versions of this Fig that are destined for the SI?

I've moved them to the SI [Google doc](https://docs.google.com/document/d/18PH0CwMHFl4YCdDBXCXS8YA_IdHmxW-2HrTqiiJA9MY/edit)

**Comment by cdsouthan** [comment]
We Zoom in 23 mins right?

**Comment by mattodd** [comment]
OK, so active compound is OSM-S-218 (has the two codes MMV669844/MMV897709 in the sheet, annoyingly) and the inactive is OSM-S-291 (MMV689968), which was the _ortho_-chloro analogue. Can't remember why we included that compound, but it was certainly inactive. Have asked Anubhav to draft a revised figure to help readability of the text.

**Comment by mattodd** [comment]
Anubhav's finished the updated Fig 10. Uploaded [here](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/tree/master/Schemes) (Fig 10 Updated 29 Mar), dragged below. Comments?

[Fig 10 Updated 29 March.pdf](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/6221221/Fig.10.Updated.29.March.pdf)

**Comment by danaklug** [comment]
Added this to the Google doc (now Fig. 9)

**Comment by danaklug** [comment]
I think we are all happy with the text and the figure has been finalized; therefore this issue can be closed.
