### ISSUE TITLE
Editing the Modeling Section 

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#38]
Hi @holeung - we're getting to an advanced draft of the Series 4 paper and need your inputs. Current version is [here](https://docs.google.com/document/d/1vlOHNo9bxmx24KmNdJz5ZmjXyVP9uZoHJcnGj181NZE/edit?usp=sharing).  

Could you please check the section (on pages 16/17). Specific things:
1) You mention that the compound docked was MMV670652, but the structure in the 2D interaction map appears not to be that, as @edwintse pointed out.
2) The homology model is the one that came out of DeRisi's lab (from Jeremy Horst), or is it your own? 
3) The picture - it'd be very good if the docking could include the OSM compound *and* SJ733 to show that overlap (as @danaklug suggested).
4) I hate to aask this now, but does the docking position explain in any way any of the SAR, in the sense of showing why some compounds are inactive, etc?

We can use this issue to discuss edits and share pictures in case that's helpful. We'll ultimately obviously need all the raw files and SI since we're getting close.

**Comment by holeung** [comment]
1. I corrected this figure in the manuscript.
2. I used my own homology model. I found several issues with the DeRisi lab model, such as broken alpha helices.
3. I have attached a new figure showing the OSM and SJ733 modeled binding sites (essentially the same).
4. Will have to get back to you on the big question of SAR. Need to find and go over my old notes carefully. My model is attached so anyone can inspect it.

![UCSF_Ng_overlap](https://user-images.githubusercontent.com/10951570/108947599-67f6e280-7626-11eb-97c7-5c3aebbe19ed.png)

[670652_bound_pdb.zip](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/6033367/670652_bound_pdb.zip)

**Comment by mattodd** [comment]
Hi @holeung - thanks for all the above and the additions to the paper.

To nail this section finally, do you think you might be able to come along to one of our editing sessions? 11 a.m. London, so maybe a little early. We could just organise another later in the day. It'd be good to run through your paragraph here and make sure we have it right, as well as to ensure that we have all the data we need for the SI section.
Yes, the idea behind SAR was just to try a molecule that was known to be inactive in the blood stage assay but which is structurally similar to the existing docked compound, e.g. one where we remove the para substitutent on the northeast phenyl ring, and check that the numbers are worse. Not essential, just nice to be able to demonstrate usefulness for future compound design.

@danaklug the picture above is the comparison with the SJ compound. It strikes me that this might be suitable for the SI, what do you think?

**Comment by danaklug** [comment]
@mattodd I'd suggest that if the compounds were rendered as ball and stick rather than space filling we could replace Figure 11 panel A in the main text since the overlap between the binding modes of these compounds is mentioned. @holeung Do you think that would be doable?

**Comment by cdsouthan** [comment]
Are we Zomming now?   I cant see anyone else in the link

OSM meeting
Monday, March 8⋅12:00 – 12:30

Description:

Topic: OSM Series 4 Manuscript
Time: Feb 8, 2021 05:00 AM Central Time (US and Canada)

Join Zoom Meeting
https://ucl.zoom.us/j/98349096123
<https://www.google.com/url?q=https://ucl.zoom.us/j/98349096123&sa=D&source=calendar&usd=2&usg=AOvVaw2Q8e1cTWnzi-fyKmFykuwT>

Meeting ID: 983 4909 6123

**Comment by danaklug** [comment]
> Are we Zomming now? I cant see anyone else in the link OSM meeting Monday, March 8⋅12:00 – 12:30  Description: Topic: OSM Series 4 Manuscript Time: Feb 8, 2021 05:00 AM Central Time (US and Canada) Join Zoom Meeting 

We can see you in the meeting now, hopefully this has been resolved for you as well!

**Comment by mattodd** [comment]
Thanks for coming along today @holeung .

To confirm some actions:

- [ ] We can include the homology model in the SI (with an acknowledgement to the previous one from Jeremy Horst. It'd be really useful if @holeung could comment on (e.g. quantitatively) how good the model is.
- [ ] Modify the above scheme to ball and stick, rather than space filling, so as to allow a comparison with SJ733. On the face of it it's pretty surprising, since the molecules are so dissimilar. A solid comparison will help.
- [ ] Mention something about the SAR that this model helps to explain, e.g. the sensitivity of the para-substituent of the triazole-attached phenyl (need something there/can tolerate something in meta/can't tolerate ortho). Can't explain everything about the SAR, but one illustrative thing would help us to say something like "this model should prove useful in ongoing compound design for further lead optimization."

**Comment by mattodd** [comment]
Hi @holeung - the additions to the paper look great. I think we're done, but can you just remind me whether we have the SI file for the homology model - is it the same as the one as the model for the modelling paper, if we have that already? once we have it we can close this issue.

**Comment by holeung** [comment]
Here is the homology model with MMV670652 docked.

[MMV670652_docked.pdb.zip](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/6438712/MMV670652_docked.pdb.zip)
