### ISSUE TITLE
Editing Session: Monday 15/3 - NO ZOOM CALL

### ISSUE THREAD

**Issue by danaklug** [OpenSourceMalaria/OSMSeries4Paper1#44]
Hi all, editing session for **Monday March 15** as of now is scheduled for the usual time (6am Boston/11am London/10pm Sydney). However @holeung we'd love have you attend to discuss the modeling session and can move to later in the day if that suits better. 

I'll confirm date/time by end of day London time on Friday and post the Zoom link then.

FYI @mattodd @edwintse @alintheopen @KiaranKirk @MedChemProf @drc007 @jonjoncardoso @cdsouthan @maratsydney et al

**Comment by danaklug** [comment]
Hi all, sorry to update last minute. No Zoom call today, but feel free to post updates and action items here for next week's meeting.

@edwintse @MedChemProf @cdsouthan

**Comment by mattodd** [comment]
Closing just to tidy up the Issues list. @holeung would be very good if you could join us for the next one on March 22nd so that we can close out your section and its associated supporting info? Happy to modify the time to better suit you if that helps?

**Comment by holeung** [comment]
Sorry, I've been in pandemic chaos here. I'll make the next meeting. If you can push it a little later in the day, I would greatly appreciate it.

**Comment by MedChemProf** [comment]
@danaklug @mattodd Was there a decision made on meeting on March 22nd? Same time as before if we are?

**Comment by mattodd** [comment]
Usual time is difficult, and would be good to get @holeung along. I could in theory manage 12:30, which is 1.5 h later than normal. Then 1 or 2pm Tue works, as does 12 or 1 on Friday. Busy week. Alternatively you go ahead without me. All these options are OK. I've updates from various people.

**Comment by danaklug** [comment]
Just created a new issue (#45) to try and schedue - if we haven't heard from @holeung about today then assume we will go with a Tuesday or Friday time slot.
