### ISSUE TITLE
Scheduling next editing session w/c 22 March

### ISSUE THREAD

**Issue by danaklug** [OpenSourceMalaria/OSMSeries4Paper1#45]
Hi all, trying to find a new time that's a bit later in the day for those joining us from the US for our editing session this week (with apologies to Sydney folks!). Some updates from Mat and hopefully a few from @holeung as well! If you'd like to attend please comment with your preferred time slot below.

**A** - Monday 22/3 8:30 am Boston/12:30 pm London/11pm Sydney
**B** - Tuesday 23/3 8 am Boston/12 pm London/11pm Sydney
**C** - Tuesday 23/2 9 am Boston/1 pm London/12am Sydney
**D** - Friday 26/3 8 am Boston/12 pm London/11pm Sydney
**E** - Friday 26/2 9 am Boston/1 pm London/12am Sydney

FYI @mattodd @edwintse @alintheopen @KiaranKirk @MedChemProf @drc007 @jonjoncardoso @cdsouthan @maratsydney et al

**Comment by mattodd** [comment]
Hi @danaklug changed D and E to Friday, I think you mean?
Would prefer the Tue/Fri slots B-E. Don't mind.

**Comment by MedChemProf** [comment]
@mattodd @danaklug I can meet for B and C. I have lecture during the D and E slots this week.

**Comment by drc007** [comment]
Did you decide on a time?

I have a manic week so choose a time and I’ll try and fit in if available

Chris

**Comment by danaklug** [comment]
We'll eliminate A since we haven't heard from a lot of people yet and I'll make the final call by EoD today US time (probably B or C as of now).

**Comment by holeung** [comment]
B or C for me.

**Comment by danaklug** [comment]
Excellent, let's go with C. Closing this issue - I'll start a new one with the Zoom link. Thanks everyone!
