### ISSUE TITLE
Editing Session: Tuesday 23/3

### ISSUE THREAD

**Issue by danaklug** [OpenSourceMalaria/OSMSeries4Paper1#46]
Hi everyone, here's the Zoom link for tomrrow's session. Reminder that the UK has not switched to Daylight Savings yet so the time difference may not be the same as usual. 

FYI @mattodd @MedChemProf @holeung @drc007 etc.

Dana Klug is inviting you to a scheduled Zoom meeting.

Topic: OSM Editing Session
Time: Mar 23, 2021 01:00 PM London

Join Zoom Meeting
https://ucl.zoom.us/j/92869339836

Meeting ID: 928 6933 9836
One tap mobile
+12532158782,,92869339836# US (Tacoma)
+13017158592,,92869339836# US (Washington DC)

Dial by your location
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
Meeting ID: 928 6933 9836
Find your local number: https://ucl.zoom.us/u/aeDjRsRnI5

**Comment by drc007** [comment]
An early reference to aniline mutagenicity and carcinogenicity

https://europepmc.org/article/med/6990249 <https://europepmc.org/article/med/6990249>

Cheers,

Chris

**Comment by cdsouthan** [comment]
Apols for not making this meeting but I'm tuning in to the NIH InChI sessions.  Brief minutes would be good, Cheers

**Comment by mattodd** [comment]
@MedChemProf added in some aniline tox references, so can close this issue.
