### ISSUE TITLE
Moving Local Github Repo in Desktop

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#5]
Hi @miike @greglandrum I wonder if you could help. Seems like should be a simple task.

For this repo (the one we're in here), which is where we'll do a bunch of writing for the next paper, I currently have the repo synched to a dropbox folder on my mac. This is apparently sub-optimal. So I want to move the local files over to a regular folder on the hard drive. I can't seem to do this. I've found [online guidance](https://forum.textpattern.io/viewtopic.php?id=46580) that implies that I need to just copy over everything to a new location, but that I need to ensure that a hidden .git folder is also copied over. If I do that will my desktop client and github (online) magically work without me tweaking anything else? Seems too easy.
However, the problem is - embarrassingly - I can't enable hidden files on my mac. Again, I've followed the [online advice](https://www.lifewire.com/display-hidden-files-in-os-x-open-and-save-dialog-boxes-2260878) about using CMD-SHIFT-period but to no avail.
So I'm stuck. Help?
Here are the options when I right-click the repo in the desktop client, by the way. I don't know what happens if I "remove" a repo - presumably that would delete local copies, and then I could re-download from the online repo into the new location on my Mac?

![screen shot 2017-08-08 at 11 11 30 am](https://user-images.githubusercontent.com/4386101/29052038-7d172a66-7c2a-11e7-92b1-d08a74b71831.png)

**Comment by miike** [comment]
Have you made changes locally that haven't been pushed to Github? If you haven't it's probably easiest to use the GUI client to reclone the repository to a different location. If you have you should be able to open the repository folder (Open in Finder) and copy the entire folder (OSMSeries4Paper1) to a different location. The `.git` folder sits underneath this so will be copied over to the new location. I'm not sure how the GUI client will handle the local copy moving but it might be okay.

**Comment by greglandrum** [comment]
I agree, I'd either copy using the finder (if you copy the main folder this should be fine) or, assuming you don't have changes you haven't already pushed to github, just reclone into the folder where you'd like the file to be.

**Comment by mattodd** [comment]
Thanks so much guys. I don't think the folder copy worked, so I just re-downloaded the repo to the correct place on the desktop. Done. This is, by the way, intended to solve the file-sharing thing associated with paper writing. We shall see.
