### ISSUE TITLE
Editing Session: Monday 29/3

### ISSUE THREAD

**Issue by danaklug** [OpenSourceMalaria/OSMSeries4Paper1#50]
Hi everyone, next editing session will be **Monday, March 29** at **12pm London.** 

(That's **7am Boston/11pm Sydney** I belive - apologies but I'm struggling a bit to keep up with who's on daylight savings time and who isn't! Please do double check your time difference from London if you plan to attend. We spring forward on 28/3.)

FYI @mattodd @edwintse @MedChemProf @drc007 @cdsouthan @maratsydney @holeung et al.

Dana Klug is inviting you to a scheduled Zoom meeting.

Topic: OSM Series 4 Paper Editing
Time: This is a recurring meeting Meet anytime

Join Zoom Meeting
https://ucl.zoom.us/j/94033228077

Meeting ID: 940 3322 8077
One tap mobile
+13462487799,,94033228077# US (Houston)
+16699006833,,94033228077# US (San Jose)

Dial by your location
        +1 346 248 7799 US (Houston)
        +1 669 900 6833 US (San Jose)
        +1 929 205 6099 US (New York)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington DC)
        +1 312 626 6799 US (Chicago)
Meeting ID: 940 3322 8077
Find your local number: https://ucl.zoom.us/u/adgvvw7gS6

**Comment by drc007** [comment]
Apologies I’m doing a webinar for the UCL MRes students, but please let me know if you need me to do anything

Chris

**Comment by cdsouthan** [comment]
Apols also,  will be on Clavirate dog and pony show call, (with Guide to
Pharmacology) on their new database offerings.  Cheers
