### ISSUE TITLE
Polishing off the Ion Regulation Data Figures with Kiaran and Adele

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#52]
Adele reached out by email to me and @edwintse. Essentially Adele has been having a look at the Na+ and pH experiments that have been performed with Series 4 compounds (mostly by Edwin during his visit, with some also tested by Adele or Adelaide Dennis).

She was asking how "Yes", "Moderate" and "No" are being defined. She suggests:

"**Yes**": gives rise to an increase in [Na+]cyt and pHcyt that is similar in magnitude to that of 50 nM cipargamin when tested at 1 uM.

"**Moderate**": gives rise to an increase in [Na+]cyt and pHcyt when tested at 1 uM and/or 5 uM, with its effect at 1 uM being lower in magnitude than that of 50 nM cipargamin

"**No**": does not affect [Na+]cyt or pHcyt when tested at 1 uM or 5 uM

In Fig. 9 of the Series 4 manuscript, MMV897713 and MMV897707 are shown as outliers in the "Yes" category. Looking at the data (attached to this issue below), Adele thinks both of these compounds actually belong in the "Moderate" category rather than the "Yes" category, as their effects at 1 uM are clearly sub-maximal.

Also, in the older version of the manuscript, in which Figure 9 had chemical structures, MMV675718 was placed in the "No" category. This compound shows evidence of PfATP4 inhibition when tested at 5 uM, so should also be 'Moderate'.

Adele's not sure if the Supplementary Figures and Tables with Na+/pH data, or cross-resistance data from Melanie in their lab, are made yet - she's happy to help more on this point.

@edwintse does all this sound OK? If yes, can you please generate updated figures, and pursue any remaining SI figs?

[1 uM SBFI PDF from dropbox.pdf](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/6375867/1.uM.SBFI.PDF.from.dropbox.pdf)
[5 uM SBFI PDF from dropbox.pdf](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/6375868/5.uM.SBFI.PDF.from.dropbox.pdf)
[BCECF PDF from dropbox.pdf](https://github.com/OpenSourceMalaria/OSMSeries4Paper1/files/6375869/BCECF.PDF.from.dropbox.pdf)

**Comment by mattodd** [comment]
Also the ANU team need to add themselves to the author list.

**Comment by edwintse** [comment]
Classifications for yes, moderate and no as stated above added to the Figure 8 caption

**Comment by danaklug** [comment]
@drc007 has kindly updated the figure for us and I've replaced the old one in the paper.
