### ISSUE TITLE
Which Journal are we Aiming For?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSMSeries4Paper1#6]
This paper is being assembled in the public domain. It is likely we might want to submit to a preprint server when we have a final version, just to garner further views, but this is not essential, given that we're essentially generating and sharing our own preprint. Nevertheless any target journal must be happy with accepting public domain work.

The paper will be heavy on medicinal chemistry and drug discovery, rather than basic biology.

Obviously the journal itself must be open access, or at least provide the option for the paper to be open access at minimal cost.

Suggestions? ACS Central Science was a very good home for the [first OSM paper](http://pubs.acs.org/doi/full/10.1021/acscentsci.6b00086).
elife? PLoS Pathogens?

_Alternatively_: we wait until we have written most of the paper and have clarity about a couple of things that are still uncertain: a) how good will our final frontrunner compound be? The effectiveness of this compound could determine a journal target. b) how much are we including on, for example, mechanism of action? So it might be easier to decide on journal once the paper is nearer completion.

Q first raised by @drc007 at OpenSourceMalaria/OSM_To_Do_List#532

**Comment by cdsouthan** [comment]
I have no strong journal preferences (and I will be a minor author anyway) but would agree we could get a lot further on into drafting before we need to decide.  NOBA preprint is a good idea (all the best folk seem to be doing it these days).   What I do say is we should choose push the J for what leading edge features **we** want (i.e. dog wagging the tail for a change)  First and foremost this means live in-line outlinking, specifically PubChem CIDs.

**Comment by MFernflower** [comment]
Does the journal of antimicrobial chemotherapy cover drug design of novel antimicrobial agents? @mattodd

**Comment by MFernflower** [comment]
Oxford's Journal of Antimicrobial Chemotherapy is rather OA friendly - I have no preferences but I avoid Elsevier like the plague

**Comment by drc007** [comment]
Is this to be a communication or a full paper? I would have thought the latter. In which case it needs to be a journal that published full experimental.

**Comment by cdsouthan** [comment]
Surely (for many reasons) a second punt for ACS Cent Sci is the frontrunner choice?
