### ISSUE TITLE
Writing of the experimental (chemistry)

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/OSMSeries4Paper1#9]
It's time to start writing the experimental section.

We're going to use GitHub to write the experimental for this paper. Details on the procedure will be posted to the wiki section. These guidelines are a work in progress and will certainly change as we become familiar with the process. We may as well make a start, and learn as we go here.

We currently have 229 compounds that @alintheopen and @edwintse have worked on locally. These files are now located in the repo. Follow @mattodd's guidelines for accessing and editing these files.

I'm guessing we may have a few stumbles as we refine this procedure. Use issues here to raise anything that needs clarification or changing.

**Comment by mattodd** [comment]
Closing this since @edwintse has advanced the SI in #54
